require 'taobao/base'
require 'taobao/exceptions/api_error'
require 'taobao/exceptions/incorrect_category_id'
require 'taobao/category'
require 'taobao/product'
require 'taobao/product_list'
require 'taobao/search'